### ISSUE TITLE
Issue in loading RcppPredBlockFrame

### ISSUE THREAD

**Issue by mani3720** [suiji/Arborist#2] opened 2016-03-02 01:29 UTC
Dear Suiji,

I am trying to use Rborist.default.R function from the ArboristR folder in github, I am getting the follwoing error while running the code: **Error in .Call("RcppPredBlockFrame", x, numIdx, facIdx, facCard, signature) : C symbol name "RcppPredBlockFrame" not in load table. **

FYI - I have loaded these two packages Rcpp and RcppArmadillo before running the Rborist.default.R code.

Background: I was using the Rborist package in CRAN for a large dataset in MRO (Microsoft Revolution open), while the Rborist function was executing well, the predict function had a error similiar to this (http://stackoverflow.com/questions/32695522/random-forest-rborist-with-large-dataset-in-r). So from the answer in the Stackoverflow i am trying to use functions in Arborist.R to run on my data. 

Please help me.  Thanks in advance.

**Comment by suiji** [comment] 2016-03-02 15:22
Dear (?),

Thank you for pointing out the problem.  I will have a look.

Regards,
Mark Seligman

**Comment by suiji** [comment] 2016-03-03 04:07
Dear mani3720,

I am unable to reproduce the problem so far.  In fact, RcppPredBlockFrame() is called whenever the training (or prediction) set is a data frame, so a failure to load should be reproducible in many of the existing test cases.

How are you installing the package?

**Comment by mani3720** [comment] 2016-03-04 04:54
Dear Suiji,
I am just copying the function code from the git hub and running the code in R, i am not sure this the correct way, please suggest me if there is a better way to use the AboristR codes.

Thanks in advance.

**Comment by suiji** [comment] 2016-03-04 17:58
The directory "ArboristBridgeR/Package" contains file "CRAN.sh".  This is a bash-shell script which yields a compressed tar-ball.  The tar-ball can be submitted to R's package-installation procedure, e.g.:  R CMD INSTALL [tar-ball name]

**Comment by suiji** [comment] 2016-03-06 01:43
Closing this issue, as it appears to be due to a nonstandard installation.
Please feel free to re-open if there is more to be done.

**Closed by suiji** 2016-03-06 01:43 UTC
